apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-dev
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: craftista:frontend-dev-stage
spec:
  project: craftista
  source:
    repoURL: https://github.com/Ariseaz/microservice-helmcharts
    targetRevision: main
    path: service-charts/frontend
    helm:
      valueFiles:
        - /env/dev/frontend/frontend-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  ignoreDifferences:
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/ports/0/nodePort
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true