apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo
  namespace: argocd
spec:
  project: default
  destination:
    namespace: kargo
    server: https://kubernetes.default.svc
  source:
    repoURL: ghcr.io/akuity/kargo-charts
    chart: kargo
    targetRevision: 1.5.0
    helm:
      parameters:
        - name: api.adminAccount.passwordHash
          value: "$$2y$$10$$AHo42TSVFtEQPlTO6lPlH.jMQKrJN9yJxsE2F6zot2SrIfnBfpwVu"
        - name: api.adminAccount.tokenSigningKey
          value: "1nOOlPfrLLyR4NZt3oeuCgdzXejgelum"
        - name: crds.install
          value: "true"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true